application: bot-10sr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: 10sr_bot.app

# http://yuribossa.hatenablog.com/entry/20090611/p1
- url: /periodic/.*
  script: 10sr_bot.app
  #login: admin


libraries:
- name: webapp2
  version: "2.5.2"
